### ISSUE TITLE
Typescript warnings during build

### ISSUE THREAD

**Issue by maximilliangeorge** [kwameopareasiedu/docts#6]
This package is awesome. I ran into a few typescript warnings when running `docts build`.

```
> docts-template@1 build
> docts build

(typescript plugin) src/foo/bar/index.ts (4:20) @rollup/plugin-typescript TS2552: Cannot find name 'DoFunction'. Did you mean 'Function'?
(typescript plugin) src/foo/bar/index.ts (4:40) @rollup/plugin-typescript TS7006: Parameter 'args' implicitly has an 'any' type.

<more warnings...>

Built 'src' into 'packages' dir. You can deploy with doctl!
```

**Comment by kwameopareasiedu** [comment]
Hi @maximilliangeorge  and thanks for using the package and finding this. It's always amazing when the community supports your package. Thanks for pointing that out. I took a break for a while which is why I couldn't respond earlier. I'll work on that to update it...

**Comment by kwameopareasiedu** [comment]
@maximilliangeorge Concerning these warnings, they can be safely ignored. It's just the rollup typescript plugin warning that the defined `DoFunctionArgs` cannot be found.

This is because when using Rollup as an API instead of on the CLI, I can't specify type roots to the ts plugin hence the warnings.

I'll close this issue now...
